create table DE_BAL
(
   BAL_GUID             varchar(36) not null comment '余额表guid',
   RG_CODE              varchar(42) not null comment '分区域维护各要素数据，实现多区域、多年度同时操作。',
   SET_YEAR             numeric(4,0) not null comment '记录当前业务年度',
   FIS_PERD             numeric(8,0) not null comment '期间',
   AGENCY_CODE          varchar(60) not null comment '单位代码，系统级科目单位为*',
   ACCT_CODE            varchar(42) not null comment '账套',
   ACCO_CODE            varchar(42) not null comment '科目',
   ACCE_CODE            varchar(42) comment '会计要素',
   CUR_CODE             varchar(42) comment '币种',
   VOU_KIND             varchar(30) comment '凭证种类 QC-期初、RC-日常、JZ-结转',
   EXPFUNC_CODE         varchar(42) comment '功能分类',
   GOVEXPECO_CODE       varchar(42) comment '政府预算经济分类',
   EXPECO_CODE          varchar(42) comment '部门预算经济分类',
   DEPPRO_CODE          varchar(42) comment '预算项目',
   PROJECT_CODE         varchar(42) comment '项目',
   FUNDTYPE_CODE        varchar(42) comment '资金性质',
   BGTSOURCE_CODE       varchar(42) comment '预算来源',
   FUNDSOURCE_CODE      varchar(42) comment '资金来源',
   PROTYPE_CODE         varchar(42) comment '项目类型',
   PAYTYPE_CODE         varchar(42) comment '支付方式',
   EXPTYPE_CODE         varchar(42) comment '支出类型',
   SETMODE_CODE         varchar(42) comment '结算方式',
   CURRENT_CODE         varchar(42) comment '往来',
   DEPARTMENT_CODE      varchar(42) comment '部门',
   EMPLOYEE_CODE        varchar(42) comment '人员',
   FATYPE_CODE          varchar(42) comment '资产类型',
   ACC_ITEM01_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM02_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM03_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM04_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM05_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM06_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM07_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM08_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM09_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM10_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM11_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM12_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM13_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM14_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM15_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM16_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM17_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM18_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM19_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM20_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM21_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM22_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM23_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM24_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM25_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM26_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM27_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM28_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM29_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM30_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM31_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM32_CODE      varchar(42) comment '自定义辅助核算',
   DR_AMT               numeric(20,2) comment '借方金额',
   CR_AMT               numeric(20,2) comment '贷方金额',
   CURDR_AMT            numeric(20,2) comment '外币借方金额',
   CURCR_AMT            numeric(20,2) comment '外币贷方金额',
   QTYDR_AMT            numeric(20,4) comment '借方数量',
   QTYCR_AMT            numeric(20,4) comment '贷方数量',
   TEMP                 VARCHAR(120),
   DATA_FROM_MODULE     VARCHAR(30),
   primary key (BAL_GUID)
);

alter table DE_BAL comment '余额表';

create index INDEX_DE_BAL on DE_BAL
(
   RG_CODE,
   SET_YEAR,
   FIS_PERD,
   AGENCY_CODE,
   ACCT_CODE,
   ACCO_CODE,
   ACCE_CODE
);



create table DE_ELE_ACCO
(
   CHR_ID               varchar(38) not null comment '唯一标识本条要素信息，使用Guid机制实现唯一区分码',
   SET_YEAR             numeric(4,0) not null comment '记录当前业务年度',
   RG_CODE              varchar(42) not null comment '分区域维护各要素数据，实现多区域、多年度同时操作。',
   AGENCY_CODE          varchar(60) not null comment '单位代码，系统级科目单位为*',
   CHR_CODE             varchar(42) not null comment '用于显示、打印、要素树的编码显示',
   CHR_NAME             varchar(200) not null default 'test' comment '用于显示、打印、要素树的名称显示',
   CHR_FULLNAME         varchar(200) comment '用于显示、打印、要素树的全称显示',
   PARENT_ID            varchar(200) comment '上级科目',
   ACCT_CODE            varchar(42) comment '账套，系统科目账套为“*”',
   ACCS_CODE            varchar(42) comment '科目体系编码',
   ACC_BAL              numeric(1,0) comment '余额方向',
   ACCE_CODE            varchar(42) comment '会计要素代码',
   AGENCY_TYPE_CODE     varchar(42) comment '多选方式适用单位类型： 1行政 2事业 3参公 其他',
   ASS_CODE             varchar(42) comment '助记码',
   ACCO_TYPE            numeric(1,0) comment '科目类型：0 普通科目； 1 现金科目； 2 银行科目； 3 零余额科目；
            4 应付科目；5 资产科目；6 应收科目',
   IS_CHANGE_ATTR       char(1) comment '是否允许修改扩展属性',
   ALLOW_CHANGE_NAME    char(1) comment '是否允许修改名称',
   REMARK               varchar(500) comment '备注',
   EXPIRE_DATE          char(1) comment '是否录入到期日',
   IS_SHOW_BILL         char(1) comment '是否显示票据号',
   DEF_CUR_CODE         varchar(42) comment '默认币种代码',
   IS_CUR               char(1) comment '是否外币核算',
   IS_QTY               char(1) comment '是否数量核算',
   QTY_DIGITS           numeric(2,0) comment '数量核算小数位数',
   QTY_UOM              varchar(4) comment '数量核算的计量单位',
   LEVEL_NUM            numeric(2,0) not null default 0 comment '显示当前本要素的级次',
   IS_LEAF              char(1) not null default '0' comment '标定是否底级叶节点',
   ENABLED              numeric(1,0) not null default 1 comment '标定本要素是否启用',
   ALLOW_ADDSUB         char(1) comment '下发后是否允许增加下级',
   CHR_CODE1            varchar(42) comment '便于查询统计提速，记录各父级CODE',
   CHR_CODE2            varchar(42) comment '便于查询统计提速，记录各父级CODE',
   CHR_CODE3            varchar(42) comment '便于查询统计提速，记录各父级CODE',
   CHR_CODE4            varchar(42) comment '便于查询统计提速，记录各父级CODE',
   CHR_CODE5            varchar(42) comment '便于查询统计提速，记录各父级CODE',
   CHR_CODE10           varchar(42) comment '便于查询统计提速，记录各父级CODE',
   CHR_CODE9            varchar(42) comment '便于查询统计提速，记录各父级CODE',
   CHR_CODE8            varchar(42) comment '便于查询统计提速，记录各父级CODE',
   CHR_CODE7            varchar(42) comment '便于查询统计提速，记录各父级CODE',
   CHR_CODE6            varchar(42) comment '便于查询统计提速，记录各父级CODE',
   CHR_ID1              varchar(38) comment '便于查询统计提速，记录各父级ID',
   CHR_ID2              varchar(38) comment '便于查询统计提速，记录各父级ID',
   CHR_ID3              varchar(38) comment '便于查询统计提速，记录各父级ID',
   CHR_ID4              varchar(38) comment '便于查询统计提速，记录各父级ID',
   CHR_ID10             varchar(38) comment '便于查询统计提速，记录各父级ID',
   CHR_ID9              varchar(38) comment '便于查询统计提速，记录各父级ID',
   CHR_ID8              varchar(38) comment '便于查询统计提速，记录各父级ID',
   CHR_ID7              varchar(38) comment '便于查询统计提速，记录各父级ID',
   CHR_ID6              varchar(38) comment '便于查询统计提速，记录各父级ID',
   CHR_ID5              varchar(38) comment '便于查询统计提速，记录各父级ID',
   FIELD1               varchar(38) comment '辅助说明项1',
   FIELD2               char(1) comment '辅助说明项2',
   FIELD3               char(1) comment '辅助说明项3',
   FIELD4               char(1) comment '辅助说明项4',
   FIELD5               char(1) comment '辅助说明项5',
   IS_DELETED           char(1) default '0' comment '标定是否删除',
   IS_EXPFUNC           char(1) comment '功能分类  0 不启用 1辅助核算 2 对应关系',
   IS_GOVEXPECO         char(1) comment '政府预算经济分类',
   IS_EXPECO            char(1) comment '部门预算经济分类',
   IS_DEPPRO            char(1) comment '预算项目',
   IS_PROJECT           char(1) comment '项目',
   IS_PROTYPE           char(1) comment '项目类型',
   IS_FUNDTYPE          char(1) comment '资金性质',
   IS_BGTSOURCE         char(1) comment '预算来',
   IS_FUNDSOURCE        char(1) comment '资金来源 0 不启用 1辅助核算 2 对应关系',
   IS_PAYTYPE           char(1) comment '支付方式',
   IS_EXPTYPE           char(1) comment '支持类型',
   IS_SETMODE           char(1) comment '结算方式',
   IS_CURRENT           char(1) comment '往来',
   IS_DEPARTMENT        char(1) comment '部门',
   IS_CASHFLOW          char(1) comment '核算现金流量',
   ACCA_CODE            varchar(42) comment '会计体系',
   PARENT_CODE          varchar(42) comment '父级编码',
   SRC_AGENCY_CODE      varchar(42) comment '数据来源单位代码',
   IS_BILLTYPE          char(1),
   BILLTYPE_CODE        varchar(42),
   ALLOW_SURPLUS        char(1) default '0' comment '是否允许盈余与结余差项',
   IS_CHECK_REGISTER    char(1) default '0' comment '备查登记',
   IS_EMPLOYEE          char(1) comment '人员',
   IS_FATYPE            char(1) comment '资产类型',
   EXPFUNC_CODE         varchar(42) comment '功能分类',
   GOVEXPECO_CODE       varchar(42) comment '政府预算经济分类',
   EXPECO_CODE          varchar(42) comment '部门预算经济分类',
   DEPPRO_CODE          varchar(42) comment '预算项目',
   PROJECT_CODE         varchar(42) comment '项目',
   PROTYPE_CODE         varchar(42) comment '项目类型',
   FUNDTYPE_CODE        varchar(42) comment '资金性质',
   BGTSOURCE_CODE       varchar(42) comment '预算来源',
   FUNDSOURCE_CODE      varchar(42) comment '资金来源',
   PAYTYPE_CODE         varchar(42) comment '支付方式',
   EXPTYPE_CODE         varchar(42) comment '支持类型',
   SETMODE_CODE         varchar(42) comment '结算方式',
   CURRENT_CODE         varchar(42) comment '往来',
   DEPARTMENT_CODE      varchar(42) comment '部门',
   EMPLOYEE_CODE        varchar(42) comment '人员',
   FATYPE_CODE          varchar(42) comment '资产类型',
   DATA_FROM_MODULE     varchar(100) comment '数据来源模块',
   ENABLE_BALANCE_CONTROL char(1) default '0' comment '启用余额控制：1启用 0不启用',
   BALANCE_CONTROL_MODE char(1) comment '余额控制方式：1禁止 2提醒',
   BALANCE_CONTROL_MONEY numeric(16,2) comment '余额控制方式金额值',
   ENABLE_LARGE_CONTROL char(1) default '0' comment '启用大额控制：1启用 0不启用',
   LARGE_CONTROL_MODE   char(1) comment '大额控制方式：1禁止 2提醒',
   LARGE_CONTROL_MONEY  numeric(16,2) comment '大额控制金额值',
   ACC_ITEM32           char(1) comment '自定义辅助核算01',
   ACC_ITEM31           char(1) comment '自定义辅助核算01',
   ACC_ITEM30           char(1) comment '自定义辅助核算01',
   ACC_ITEM29           char(1) comment '自定义辅助核算01',
   ACC_ITEM28           char(1) comment '自定义辅助核算01',
   ACC_ITEM27           char(1) comment '自定义辅助核算01',
   ACC_ITEM26           char(1) comment '自定义辅助核算01',
   ACC_ITEM25           char(1) comment '自定义辅助核算01',
   ACC_ITEM24           char(1) comment '自定义辅助核算01',
   ACC_ITEM23           char(1) comment '自定义辅助核算01',
   ACC_ITEM22           char(1) comment '自定义辅助核算01',
   ACC_ITEM21           char(1) comment '自定义辅助核算01',
   ACC_ITEM20           char(1) comment '自定义辅助核算01',
   ACC_ITEM19           char(1) comment '自定义辅助核算01',
   ACC_ITEM18           char(1) comment '自定义辅助核算01',
   ACC_ITEM17           char(1) comment '自定义辅助核算17',
   ACC_ITEM16           char(1) comment '自定义辅助核算16',
   ACC_ITEM15           char(1) comment '自定义辅助核算15',
   ACC_ITEM14           char(1) comment '自定义辅助核算14',
   ACC_ITEM13           char(1) comment '自定义辅助核算13',
   ACC_ITEM12           char(1) comment '自定义辅助核算12',
   ACC_ITEM11           char(1) comment '自定义辅助核算11',
   ACC_ITEM10           char(1) comment '自定义辅助核算10',
   ACC_ITEM09           char(1) comment '自定义辅助核算09',
   ACC_ITEM08           char(1) comment '自定义辅助核算08',
   ACC_ITEM07           char(1) comment '自定义辅助核算07',
   ACC_ITEM06           char(1) comment '自定义辅助核算06',
   ACC_ITEM05           char(1) comment '自定义辅助核算05',
   ACC_ITEM04           char(1) comment '自定义辅助核算04',
   ACC_ITEM03           char(1) comment '自定义辅助核算03',
   ACC_ITEM01           char(1) comment '自定义辅助核算02',
   ACC_ITEM02           char(1) comment '自定义辅助核算01',
   ACC_ITEM01_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM02_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM03_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM04_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM05_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM06_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM07_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM08_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM09_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM10_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM11_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM12_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM13_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM14_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM15_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM16_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM17_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM18_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM19_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM32_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM31_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM30_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM29_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM28_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM27_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM26_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM25_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM24_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM23_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM22_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM20_CODE      varchar(42) comment '自定义辅助核算',
   ACC_ITEM21_CODE      varchar(42) comment '自定义辅助核算',
   CREATE_DATE          varchar(19) comment '创建时间 YYYY-MM-DD HH:MM:SS',
   CREATE_USER          varchar(42) comment '创建用户',
   LATEST_OP_DATE       varchar(19) comment '最后修改时间： YYYY-MM-DD HH:MM:SS',
   LATEST_OP_USER       varchar(42) comment '最后修改用户',
   LAST_VER             numeric(8,0) comment '最后版本：每次+1',
   USE_COUNT            numeric(8,0) default 0 comment '使用次数',
   primary key (CHR_ID)
);

alter table DE_ELE_ACCO comment '会计科目';