lc:
  log:
    enable: true
crux:
  sqlaspect:
    dbtype: mysql
    enabled: true

server:
  port: 12580

mybatis:
  config-location: "classpath:mybatis/mybatis.cfg.xml"         # mybatis配置文件所在路径
  mapper-locations:
    - "classpath*:mybatis/mapper/**/*.xml"                     # mapper映射文件
  type-aliases-package: lc.entity                              # 别名类所在包

spring:
  application:
    name: microservice-lcintegratedproject                #微服务的名字
  ###################以下为druid增加的配置#####################
  #######  driverClassName:com.mysql.jdbc.Driver
  ####### url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver                     # mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource                # 当前数据源操作类型
    url: jdbc:p6spy:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
    username: test                                              # mysql 本地环境 用户：root 密码 Liu123456
    password: 1
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000                        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000                          # 配置一个连接在池中最小生存的时间，单位是毫秒
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true                                 # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j                                     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true                                 # 合并多个DruidDataSource的监控数据
    ###############以上为配置druid添加的配置#######################                                             # 数据库连接池的最小维持连接数
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true     #  消息发送到交换机确认机制，是否确认回调
    publisher-returns: true      #  启动消息失败返回，比如路由不到队列时触发回调
    listener:
      simple:
        acknowledge-mode: manual

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  logger:
    enabled: true
    dbtype: mysql
    only-error: false
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
    username: test
    password: 1
    maximum-pool-size: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: microservicecloud-provider-lcintegratedproject     #自定义服务名称信息
    prefer-ip-address: true                                         #访问路径可以显示IP地址
info:
  app.name: microservicecloud-lcintegratedproject
  company.name: www.lc.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
logging:
  level:
    com.codingapi: debug