server:
  port: 7001
spring:
  application:
    name: microservicecloud-provider
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver                     # mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource                # 当前数据源操作类型
    url: jdbc:p6spy:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
    username: test
    password: 1
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML

mybatis:
  config-location: "classpath:mybatis/mybatis.cfg.xml"        # mybatis配置文件所在路径
  mapper-locations:
    - "classpath:mybatis/mapper/**/*.xml"                     # mapper映射文件
  type-aliases-package: lc.entity            # 别名类所在包

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
  publisher-confirms: true

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  logger:
    enabled: true
    dbtype: mysql
    only-error: false
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
    username: test
    password: 1
    maximum-pool-size: 3
crux:
  sqlaspect:
    dbtype: mysql
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: microservicecloud-provider7001     #自定义服务名称信息
    prefer-ip-address: true                        #访问路径可以显示IP地址
info:
  app.name: microservicecloud-provider
  company.name: www.lc.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

logging:
  level:
    com.codingapi: debug