##80多区划数据源动态配置-hikari
datasource:
  config:
    datasources:
      -   id: dfdatasource
          driverClassName: com.p6spy.engine.spy.P6SpyDriver
          jdbcUrl: jdbc:p6spy:oracle:thin:@${env.db.dbdf.host}:${env.db.dbdf.port}/${env.db.dbdf.dbname}
          username: ${env.db.dbdf.username}
          password: ${env.db.dbdf.password}
          connectionTimeout: 300000
          maximum-pool-size: 200
          minimum-idle: 30
          connectionTestQuery: select 1 from dual

      -   id: dfaccountdatasource
          driverClassName: com.p6spy.engine.spy.P6SpyDriver
          jdbcUrl: jdbc:p6spy:oracle:thin:@${env.db.dbdfaccount.host}:${env.db.dbdfaccount.port}/${env.db.dbdfaccount.dbname}
          username: ${env.db.dbdfaccount.username}
          password: ${env.db.dbdfaccount.password}
          connectionTimeout: 300000
          maximum-pool-size: 100
          minimum-idle: 5
          connectionTestQuery: select 1 from dual
      -   id: dfreaddatasource
          driverClassName: com.p6spy.engine.spy.P6SpyDriver
          jdbcUrl: jdbc:p6spy:oracle:thin:@${env.db.dbdfall.host}:${env.db.dbdfall.port}/${env.db.dbdfall.dbname}
          username: ${env.db.dbdfall.username}
          password: ${env.db.dbdfall.password}
          connectionTimeout: 300000
          maximum-pool-size: 100
          minimum-idle: 5
          connectionTestQuery: select 1 from dual

    multiDataSource:
      id: multiDataSource
      dbType: Oracle
      defaultDataSource: dfdatasource
      dataSources:
        -   beanId: dfdatasource
            key: 360000000#2020
        -   beanId: dfreaddatasource
            key: 360000000#2020#read
        -   beanId: dfaccountdatasource
            key: 360000000#2020#account
        -   beanId: dfdatasource
            key: 360192000#2020
        -   beanId: dfreaddatasource
            key: 360192000#2020#read
        -   beanId: dfaccountdatasource
            key: 360192000#2020#account